---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agents
  namespace: agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agents
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/auth-path: "<PATCH_ME>"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "agents"
        vault.hashicorp.com/agent-inject-secret-config.properties: "agents/config"
        vault.hashicorp.com/agent-inject-template-config.properties: |
          {{- with secret "agents/config" }}
          {{- range $k, $v := .Data.data }}
          {{ $k }}: {{ $v }}
          {{- end }}
          {{- end }}
      labels:
        app: agents
    spec:
      containers:
      - image: quay.io/ablock/agents
        imagePullPolicy: Always
        name: agents
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
      serviceAccountName: agents
