---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: openshift-ingress
spec:
  # Name of the secret to hold the issued certificate
  secretName: ingress-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
  - "Red Hat PFE Engineering"
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
  - server auth
  - client auth
  dnsNames:
  - <PATCH_ME>
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production-route53
    group: cert-manager.io
