---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patches:
- target:
    group: cert-manager.io
    version: v1
    kind: ClusterIssuer
    name: letsencrypt-production-route53
  patch: |-
    - op: replace
      path: /spec/acme/solvers/0/selector/dnsZones/0
      value: ch69t-prod.sandbox1624.opentlc.com
    - op: replace
      path: /spec/acme/solvers/0/dns01/route53/region
      value: us-west-1
    - op: replace
      path: /spec/acme/solvers/0/dns01/route53/hostedZoneID
      value: Z2FILSB69DY752
    - op: replace
      path: /spec/acme/solvers/0/dns01/route53/accessKeyID
      value: 

- target:
    group: cert-manager.io
    version: v1
    kind: Certificate
    namespace: openshift-ingress
    name: ingress-cert
  patch: |-
    - op: replace
      path: /spec/dnsNames/0
      value: '*.apps.ch69t-prod.sandbox1624.opentlc.com'
