---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acm-hibernator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acm-hibernator
subjects:
- kind: ServiceAccount
  name: hibernator
  namespace: acm-hibernator
